<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>npr</string>
		<string>npr-logic</string>
		<string>nprp</string>
		<string>nprr</string>
		<string>nprs</string>
	</array>
	<key>name</key>
	<string>MMM CS-NPR</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Double Quoted Strings</string>
			<key>include</key>
			<string>#string_double</string>
		</dict>
		<!-- <dict>
			<key>comment</key>
			<string>Single Quoted Strings</string>
			<key>include</key>
			<string>#string_single</string>
		</dict> -->
		<!-- <dict>
			<key>comment</key>
			<string>String List</string>
			<key>include</key>
			<string>#string_list</string>
		</dict> -->

		<dict>
			<key>begin</key>
			<string>^\s*(:List)\s([^()]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.keyword.focus</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.attribute.focus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\s*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list_member</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.focus</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>white.focus</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Code Members</string>
			<key>match</key>
			<string>^\s*(:[A-Za-z]+)\s([^()]+)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Translator Parameters</string>
			<key>match</key>
			<string>:\w+\s+</string>
			<key>name</key>
			<string>white.focus</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Focus Function</string>
			<key>include</key>
			<string>#break</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Focus Function</string>
			<key>include</key>
			<string>#focus_function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>FS Control Functions</string>
			<key>include</key>
			<string>#fs_control</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>lower Case List Set</string>
			<key>include</key>
			<string>#fs_lowerlist</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Upper Case List Set</string>
			<key>include</key>
			<string>#fs_upperlist</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>FS Functions</string>
			<key>include</key>
			<string>#fs_function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>FS Functional Forms</string>
			<key>include</key>
			<string>#fs_functional</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>FS Formatting Functions</string>
			<key>include</key>
			<string>#fs_format</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>FS Global Variables</string>
			<key>include</key>
			<string>#fs_global</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>FS Local Variables</string>
			<key>include</key>
			<string>#fs_local</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numbers</string>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operators and Comparators</string>
			<key>include</key>
			<string>#operator</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Assigns (Goes to's)</string>
			<key>include</key>
			<string>#assign</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>white.focus</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>white.value.focus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s{2,}[A-Za-z]{3,})\s+([\sA-Za-z.\d]*)</string>
		</dict>
	<!-- 	<dict>
			<key>comment</key>
			<string>Workaround for Translator Components</string>
			<key>match</key>
			<string>^\s{2,}[A-Za-z]{3,}\s+</string>
			<key>name</key>
			<string>entity.attribute.focus</string>
		</dict> -->
		<!-- <dict>
			<key>begin</key>
			<string>;</string>
			<key>comment</key>
			<string>Orphaned code</string>
			<key>contentName</key>
			<string>comment.focus</string>
			<key>end</key>
			<string>^\s*(?=[:#])</string>
		</dict> -->
		<!-- <dict>
			<key>comment</key>
			<string>Exclued ;'s in {}'s from Orphaned code match</string>
			<key>include</key>
			<string>#nested_braces</string>
		</dict> -->
	</array>
	<key>repository</key>
	<dict>
		<key>assign</key>
		<dict>
			<key>comment</key>
			<string>Assigns (Goes to's)</string>
			<key>match</key>
			<string>(\^)</string>
			<key>name</key>
			<string>constant.focus</string>
		</dict>
		<key>break</key>
		<dict>
			<key>begin</key>
			<string>(@)(Break)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.debug.focus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>^ *;.*$</string>
			<!-- <string>//.*$</string> -->
			<key>name</key>
			<string>comment.focus</string>
		</dict>
		<key>focus_function</key>
		<dict>
			<key>begin</key>
			<string>(@)(\w+)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.function.focus</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Focus Function</string>
			<key>end</key>
			<string>(\w*)(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.function.focus</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nested_parens</string>
				</dict>
			</array>
		</dict>
		<key>fs_control</key>
		<dict>
			<key>comment</key>
			<string>FS Control Functions</string>
			<key>match</key>
			<string>IF|DO</string>
			<key>name</key>
			<string>keyword.function.fs.focus</string>
		</dict>
		<key>fs_format</key>
		<dict>
			<key>comment</key>
			<string>FS Formatting Functions</string>
			<key>match</key>
			<string>:\d+[LRCZDIN]?</string>
			<key>name</key>
			<string>keyword.function.fs.focus</string>
		</dict>
		<key>fs_function</key>
		<dict>
			<key>comment</key>
			<string>FS Functions</string>
			<key>match</key>
			<string>@[A-Z\.]*</string>
			<key>name</key>
			<string>entity.focus</string>
		</dict>
		<key>fs_functional</key>
		<dict>
			<key>comment</key>
			<string>FS Functional Forms</string>
			<key>match</key>
			<string>@~?[!#$%&amp;*+-/&lt;=&gt;?\|]?</string>
			<key>name</key>
			<string>white.focus</string>
		</dict>
		<key>fs_global</key>
		<dict>
			<key>comment</key>
			<string>FS Global Variables</string>
			<key>match</key>
			<string>(?&lt;!@)[a-z]</string>
			<key>name</key>
			<string>invalid.focus</string>
		</dict>
		<key>fs_local</key>
		<dict>
			<key>comment</key>
			<string>FS Local Variables</string>
			<key>match</key>
			<string>(?&lt;!@)[A-Z]</string>
			<key>name</key>
			<string>storage.focus</string>
		</dict>
		<key>fs_lowerlist</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.focus</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>lower Case List Set</string>
			<key>match</key>
			<string>@[a-z](\d+)</string>
			<key>name</key>
			<string>invalid.focus</string>
		</dict>
		<key>fs_upperlist</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.focus</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Upper Case List Set</string>
			<key>match</key>
			<string>@[A-Z](\d+)</string>
			<key>name</key>
			<string>keyword.function.fs.focus</string>
		</dict>
		<key>list_member</key>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>comment</key>
			<string>String List</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;={)[^{}|]+(?=|)</string>
					<key>name</key>
					<string>string.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=|)[^{}|]+(?=|)</string>
					<key>name</key>
					<string>string.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=|)[^{}|]+(?=})</string>
					<key>name</key>
					<string>string.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;={)[^{}|]+(?=})</string>
					<key>name</key>
					<string>string.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=|)[^{}|]+(?={)</string>
					<key>name</key>
					<string>invalid.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;={)[^{}|]+(?={)</string>
					<key>name</key>
					<string>invalid.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=})[^{}|]+(?=|)</string>
					<key>name</key>
					<string>invalid.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=})[^{}|]+(?=})</string>
					<key>name</key>
					<string>invalid.focus</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list_member2</string>
				</dict>
			</array>
		</dict>
		<key>list_member2</key>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>comment</key>
			<string>String List</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;={)[^{}|]+(?=|)</string>
					<key>name</key>
					<string>string.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=|)[^{}|]+(?=|)</string>
					<key>name</key>
					<string>string.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=|)[^{}|]+(?=})</string>
					<key>name</key>
					<string>string.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;={)[^{}|]+(?=})</string>
					<key>name</key>
					<string>string.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=|)[^{}|]+(?={)</string>
					<key>name</key>
					<string>invalid.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;={)[^{}|]+(?={)</string>
					<key>name</key>
					<string>invalid.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=})[^{}|]+(?=|)</string>
					<key>name</key>
					<string>invalid.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=})[^{}|]+(?=})</string>
					<key>name</key>
					<string>invalid.focus</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list_member</string>
				</dict>
			</array>
		</dict>
		<key>nested_braces</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#break</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#focus_function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fs_control</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fs_lowerlist</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fs_upperlist</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fs_function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fs_functional</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fs_format</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fs_global</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fs_local</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#assign</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nested_braces</string>
				</dict>
			</array>
		</dict>
		<key>nested_parens</key>
		<dict>
			<key>begin</key>
			<string>(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>nohilight.focus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>nohilight.focus</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity.attribute.focus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nested_parens</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>comment</key>
			<string>Numbers</string>
			<key>match</key>
			<string>(\d+)</string>
			<key>name</key>
			<string>constant.focus</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>comment</key>
			<string>Operators and Comparators</string>
			<key>match</key>
			<string>(\-|\+|\*|\/|\.|:|%|\&amp;|=|~=|&lt;=|&gt;+|&lt;|&gt;)</string>
			<key>name</key>
			<string>constant.focus</string>
		</dict>
		<key>string_double</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>Double Quoted Strings</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.focus</string>
		</dict>
		<key>string_list</key>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>comment</key>
			<string>String List</string>
			<key>end</key>
			<string>'</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=`)[^`',]+(?=,)</string>
					<key>name</key>
					<string>string.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=,)[^`',]+(?=,)</string>
					<key>name</key>
					<string>string.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=,)[^`',]+(?=')</string>
					<key>name</key>
					<string>string.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=`)[^`',]+(?=')</string>
					<key>name</key>
					<string>string.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=,)[^`',]+(?=`)</string>
					<key>name</key>
					<string>invalid.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=`)[^`',]+(?=`)</string>
					<key>name</key>
					<string>invalid.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=')[^`',]+(?=,)</string>
					<key>name</key>
					<string>invalid.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=')[^`',]+(?=')</string>
					<key>name</key>
					<string>invalid.focus</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_list2</string>
				</dict>
			</array>
		</dict>
		<key>string_list2</key>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>comment</key>
			<string>String List</string>
			<key>end</key>
			<string>'</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=`)[^`',]+(?=,)</string>
					<key>name</key>
					<string>string2.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=,)[^`',]+(?=,)</string>
					<key>name</key>
					<string>string2.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=,)[^`',]+(?=')</string>
					<key>name</key>
					<string>string2.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=`)[^`',]+(?=')</string>
					<key>name</key>
					<string>string2.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=,)[^`',]+(?=`)</string>
					<key>name</key>
					<string>invalid.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=`)[^`',]+(?=`)</string>
					<key>name</key>
					<string>invalid.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=')[^`',]+(?=,)</string>
					<key>name</key>
					<string>invalid.focus</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=')[^`',]+(?=')</string>
					<key>name</key>
					<string>invalid.focus</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_list</string>
				</dict>
			</array>
		</dict>
		<key>string_single</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>comment</key>
			<string>Single Quoted Strings</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.focus</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.focus</string>
	<key>uuid</key>
	<string>4f6aa884-ce38-4aef-b445-06573e143ced</string>
</dict>
</plist>
